import { useQuery } from '@tanstack/react-query';
import api from '../api/client';
import { FileText, Download } from 'lucide-react';

export default function GeneratedLedgers() {
  const { data: history, isLoading } = useQuery({
    queryKey: ['ledger-history'],
    queryFn: () => api.get('/ledger/history').then(r => r.data)
  });

  const redownload = (regNo: string) => {
    api.get(`/ledger/student/${regNo}/pdf`, { responseType: 'blob' }).then(res => {
      const url = URL.createObjectURL(new Blob([res.data], { type: 'application/pdf' }));
      const a = document.createElement('a');
      a.href = url;
      a.download = `fee_ledger_${regNo}.pdf`;
      a.click();
      URL.revokeObjectURL(url);
    });
  };

  return (
    <div>
      <div className="mb-6">
        <h1 className="page-title">Generated Ledgers</h1>
        <p className="page-subtitle">History of all generated fee ledger PDFs</p>
      </div>

      <div className="table-container card">
        <table className="table">
          <thead>
            <tr>
              <th>#</th>
              <th>Type</th>
              <th>Reg. No.</th>
              <th>Student Name</th>
              <th>Students</th>
              <th>Generated By</th>
              <th>Date & Time</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            {isLoading ? (
              <tr><td colSpan={8} className="text-center py-10 text-gray-400">Loading...</td></tr>
            ) : !history?.length ? (
              <tr><td colSpan={8} className="text-center py-10 text-gray-400">
                <FileText size={32} className="mx-auto mb-2 opacity-30" />
                No ledgers generated yet
              </td></tr>
            ) : (
              history.map((h: any) => (
                <tr key={h.id}>
                  <td className="text-gray-400">{h.id}</td>
                  <td>
                    <span className={`badge ${h.generation_type === 'individual' ? 'badge-blue' : 'badge-gray'}`}>
                      {h.generation_type}
                    </span>
                  </td>
                  <td><span className="font-mono text-xs text-blue-700 font-semibold">{h.registration_no || '-'}</span></td>
                  <td>{h.student_name || (h.generation_type === 'bulk' ? 'Multiple Students' : '-')}</td>
                  <td className="text-center">{h.student_count || (h.generation_type === 'individual' ? 1 : '-')}</td>
                  <td className="text-gray-500">{h.generated_by_name || '-'}</td>
                  <td className="text-xs text-gray-400">
                    {new Date(h.created_at).toLocaleString('en-IN', {day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'})}
                  </td>
                  <td>
                    {h.registration_no && h.generation_type === 'individual' && (
                      <button className="btn-secondary text-xs py-1 px-2" onClick={() => redownload(h.registration_no)}>
                        <Download size={12} /> Re-download
                      </button>
                    )}
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
}
